web:
  image: ruby:latest
  working_dir: /app/user
  volumes:
    - '../../:/app/user'
  ports:
    - '3000:3000'
  command: bash -c 'cd examples/sinatra && make'

curl:
  image: ruby:latest # because you already have it
  working_dir: /app/user
  volumes:
    - 'Makefile:/app/user/Makefile'
  links:
    - web
  command: make curl
