default:
	bundle install
	bundle exec ruby ./app.rb

curl:
	sleep 10
	@echo "\n----"
	curl -s http://web:3000
	@echo "\n----"
	curl -s http://web:3000
	@echo "\n----"
	curl -s http://web:3000
	@echo "\n----"
	curl -s http://web:3000
